apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    resources:
      requests:
        cpu: 250m
    image: quay.io/coreos/hyperkube:{{ k8s_ver }}
    command:
    - /hyperkube
    - apiserver
    - --bind-address=0.0.0.0
    - --etcd-servers={% set comma = joiner(",") %}{% for host in groups['etcd'] %}{{ comma() }}https://{{ hostvars[host]['ansible_eth0']['ipv4']['address'] }}:2379{% endfor %}

    - --allow-privileged=true
    - --cloud-config=/etc/kubernetes/azure.json
    - --cloud-provider=azure
    - --service-cluster-ip-range={{ service_ip_range }}
    - --secure-port=443
    - --advertise-address={{ ansible_default_ipv4.address }}
    - --admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota
    - --etcd-cafile=/etc/kubernetes/ssl/ca.pem
    - --etcd-certfile=/etc/kubernetes/ssl/apiserver.pem
    - --etcd-keyfile=/etc/kubernetes/ssl/apiserver-key.pem
    - --tls-cert-file=/etc/kubernetes/ssl/apiserver.pem
    - --tls-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem
    - --client-ca-file=/etc/kubernetes/ssl/ca.pem
    - --token-auth-file=/etc/kubernetes/tokens.csv
    - --service-account-key-file=/etc/kubernetes/ssl/apiserver-key.pem
    - --runtime-config=extensions/v1beta1=true,extensions/v1beta1/thirdpartyresources=true
    - --kubelet-client-certificate=/etc/kubernetes/ssl/apiserver.pem
    - --kubelet-client-key=/etc/kubernetes/ssl/apiserver-key.pem
    ports:
    - containerPort: 443
      hostPort: 443
      name: https
    - containerPort: 8080
      hostPort: 8080
      name: local
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl
      name: ssl-certs-kubernetes
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
    - mountPath: /etc/kubernetes/tokens.csv
      name: ssl-tokens-kubernetes
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/ssl
    name: ssl-certs-kubernetes
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host
  - hostPath:
      path: /etc/kubernetes/tokens.csv
    name: ssl-tokens-kubernetes
