#cloud-config
coreos:
  update:
    reboot-strategy: "off"
  units:
    - name: update-engine.service
      command: stop
    - name: locksmithd.service
      command: stop
write_files:
  - path: /etc/kubernetes/azure.json
    permissions: "0644"
    owner: "root"
    content: |
      {
          "tenantId": "${tenant_id}",
          "subscriptionId": "${subscription_id}",
          "aadClientId": "${client_id}",
          "aadClientSecret": "${client_secret}",
          "resourceGroup": "${resource_group}",
          "location": "${location}",
          "subnetName": "${subnet_name}",
          "securityGroupName": "${security_group}",
          "vnetName": "${vnet_name}",
          "routeTableName": "${route_table_name}"
      }
