apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    certificate-authority: /etc/kubernetes/ssl/ca.pem
    server: https://{{ master_fqdn }}
users:
- name: proxy
  user:
    client-certificate: /etc/kubernetes/ssl/proxy.pem
    client-key: /etc/kubernetes/ssl/proxy-key.pem
contexts:
- context:
    cluster: local
    user: proxy
  name: proxy-context
current-context: proxy-context
