apiVersion: v1
data:
  proxy-connect-timeout: "15"
  proxy-read-timeout: "600"
  proxy-send-imeout: "600"
  hsts-include-subdomains: "false"
  proxy-body-size: "64m"
  server-name-hash-bucket-size: "256"
  proxy-real-ip-cidr: 0.0.0.0/32
kind: ConfigMap
metadata:
  namespace: nginx-ingress
  name: nginx
